# 启用单词提示
EnableWordHint=False
# 在使用物理键盘时启用单词提示
WordHintOnPhysicalKeyboard=False
# 根据编辑器属性禁用单词提示
EditorControlledWordHint=True
# 单词提示页大小
PageSize=10
# 选词修饰键
ChooseModifier=Alt
# 在单词间插入空格
InsertSpace=True

